import { mongoConfig } from "../../database/mongo/mongo.config.js";
import { createConnection } from "../../database/mongo/mongo.connection.js";

export const masterClientSchema = () => {
  const collection = mongoConfig.collection.master_client;
  const schema = {
    _id: { required: true, type: String },
    company_npwp: { type: String, unique: true },
    jenis_wp: { type: Number, default: 1 },
    company_name: { type: String, required: true },
    bentuk_badan_hukum: { type: Number },
    negara_asal: { type: String },
    kegiatan_utama: { type: String },
    kewarganegaraan: { type: String },
    bahasa: { type: String },

    status_npwp: { type: Number, default: 1 },
    tanggal_daftar: { type: Date, default: new Date(Date.now()) },
    tanggal_aktivasi: { type: Date, default: new Date(Date.now()) },
    status_pkp: { type: Number },
    tanggal_pengukuhan_pkp: { type: Date },
    kantor_wilayah_djp: { type: String },
    kantor_pelayanan_pajak: { type: Number },
    seksi_pengawasan: { type: Number },
    status: { required: true, type: Number, default: 1 },

    nomor_keputusan_pengesahan: { type: String },
    tanggal_keputusan_pengesahan: { type: Date },
    nomor_keputusan_pengesahan_perubahan: { type: String },
    tanggal_keputusan_pengesahan_perubahan: { type: Date },
    nomor_akta_pendirian: { type: String },
    tempat_pendirian: { type: String },
    tanggal_pendirian: { type: Date },
    nik_notaris: { type: String },
    nama_notaris: { type: String },
    jenis_perusahaan: { type: String },
    modal_dasar: { type: Number },
    modal_ditempatkan: { type: Number },
    modal_disetor: { type: Number },

    nomor_paspor: { type: String },
    tempat_lahir: { type: String },
    tanggal_lahir: { type: Date },
    jenis_kelamin: { type: Boolean },
    status_perkawinan: { type: String },
    status_hubungan_keluarga: { type: String },
    nama_kepala: { type: String },
    nik_kepala: { type: String },
    agama: { type: String },
    pekerjaan: { type: String },
    nama_ibu_kandung: { type: String },
    nomor_kartu_keluarga: { type: String },
    kode_klu: { type: String },

    data_alamat: {
      _id: { type: String, required: true, unique: true },
      negara: { type: String },
      jenis_alamat: { type: Number },
      alamat: { type: String },
      rt: { type: String },
      rw: { type: String },
      provinsi: { type: Number },
      kabupaten: { type: Number },
      kecamatan: { type: Number },
      desa: { type: Number },
      kode_area: { type: Number },
      kode_pos: { type: Number },
      data_geometrik: { type: String },
      disewa: { type: Number },
      identitas_pemilik: { type: String },
      nama_pemilik: { type: String },
      tanggal_mulai_sewa: { type: Date },
      tanggal_sewa_berakhir: { type: Date },
      tanggal_mulai: { type: Date },
      tanggal_berakhir: { type: Date },
      kode_kpp: { type: Number },
      bagian_pengawasan: { type: Number },

      identitas_pic: { type: String },
      nama_pic: { type: String },
      kewarganegaraan_pic: { type: String },
      nama_nitku: { type: String },
      jenis_nitku: { type: String },
      kode_klu: { type: String },
    },

    merek: { type: String },
    jumlah_karyawan: { type: String },
    metode_pembukuan: { type: String },
    mata_uang_pembukuan: { type: String },
    periode_pembukuan: { type: String },
    omset_pertahun: { type: String },
    bruto: { type: Number },

    data_kontak: {
      _id: { type: String, unique: true, required: true },
      jenis_kontak: { type: String },
      nomor_telepon: { type: String },
      nomor_handphone: { type: String },
      nomor_faksimile: { type: String },
      email: { type: String },
      website: { type: String },
      keterangan: { type: String },
      tanggal_mulai: { type: Date },
      tanggal_berakhir: { type: Date },
    },

    orang_terkait: {
      _id: { type: String, unique: true, required: true },
      jenis_pihak: { type: String },
      pic: { type: Number },
      jenis_orang_terkait: { type: String },
      sub_jenis_orang_terkait: { type: String },
      identitas: { type: String },
      name: { type: String },
      nomor_paspor: { type: String },
      kewarganegaraan: { type: String },
      negara_asal: { type: String },
      email: { type: String },
      nomor_telepon: { type: String },
      tanggal_mulai: { type: Date },
      tanggal_berakhir: { type: Date },
      jenis_wp: { type: String },
      keterangan: { type: String },
      kriteria_pemilik_manfaat: { type: String },
    },

    tempat_kegiatan_usaha: {
      _id: { required: true, unique: true, type: String },
      nitku: { type: String },
      jenis_tku: { type: String },
      nama_tku: { type: String },
      deskripsi_tku: { type: String },
      klu_tku: { type: String },
      deskripsi_klu_tku: { type: String },
      pic_tku: { type: String },
      alamat: { type: String },
      rt: { type: String },
      rw: { type: String },
      provinsi: { type: String },
      kabupaten: { type: String },
      kecamatan: { type: String },
      desa: { type: String },
      kode_kpp: { type: String },
      kode_wilayah: { type: String },
      kode_pos: { type: String },
      data_geometrik: { type: String },
      seksi_pengawasan: { type: String },
      lokasi_disewa: { type: Number },
      identitas_pemilik: { type: String },
      nama_pemilik: { type: String },
      tanggal_awal_sewa: { type: Date },
      tanggal_akhir_sewa: { type: Date },
      tanggal_mulai: { type: Date },
      tanggal_berakhir: { type: Date },
      toko_retail: { type: Number },
      kawasan_bebas: { type: Number },
      kawasan_ekonomi_khusus: { type: Number },
      tempat_penimbunan_berikat: { type: Number },
      nomor_surat: { type: String },
      tanggal_awal_keputusan: { type: Date },
      tanggal_akhir_keputusan: { type: Date },
      kantor_virtual: { type: Number },
      alamat_utama_pkp: { type: Number },
    },

    data_bank: {
      _id: { type: String, required: true, unique: true },
      nama_bank: { type: String },
      nomor_rekening: { type: String },
      jenis_rekening: { type: String },
      nama_pemilik_rekening: { type: String },
      tanggal_mulai: { type: Date },
      tanggal_berakhir: { type: Date },
    },

    nomor_eksternal: {
      _id: { type: String, required: true, unique: true },
      tipe: { type: String },
      nomor_identifikasi: { type: String },
      tanggal_mulai: { type: Date },
      tanggal_berakhir: { type: Date },
    },

    data_keluarga: {
      _id: { type: String, required: true, unique: true },
      nik: { type: String },
      jenis_kelamin: { type: String },
      tempat_lahir: { type: String },
      tanggal_lahir: { type: Date },
      nomor_kk: { type: String },
      nama: { type: String },
      status_keluarga: { type: String },
      pekerjaan: { type: String },
      status_unit_pajak: { type: String },
      status_ptkp: { type: String },
      tanggal_mulai: { type: Date },
      tanggal_berakhir: { type: Date },
    },
  };

  const options = {
    _id: false,
    timestamps: true,
  };

  return createConnection({
    collection,
    schema,
    options,
  });
};
